### ISSUE TITLE
test on Windows 10 - Ubuntu Bash Fail

### ISSUE THREAD

**Issue by devozanges** [alex-saunders/glicky#31]
I try to test this lib under my bash for Windows 10, but I've an error at start...

```
root@MY-PC:/mnt/d/dev/glicky# glicky
/usr/lib/node_modules/glicky/bin/index.js:39
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
```
if anyone knows what's going on....
thx

**Comment by alex-saunders** [comment]
Hi @devozanges , what version of node are you running?

**Comment by devozanges** [comment]
npm@3.10.10
